services:

  postgres: 
    container_name: av_postgres
    image: postgres
    restart: always
    environment: 
        POSTGRES_DB: animal_volunteer
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
    - 5434:5432
    volumes:
    - av_postgres-data:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: av_seq-logs
    restart: always
    environment: 
      - ACCEPT_EULA=Y
    ports: 
      - 5341:5341
      - 8081:80

  mongodb:
    image: mongo
    container_name: av_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - 27017:27017
    volumes:
      - av_mongo_data:/data/db

  minio:
   container_name: av_minio
   image: minio/minio:latest
   ports:
    - 9000:9000
    - 9001:9001
   volumes:
    - av_minio_data:/data
   command: server --console-address ":9001" /data
   
volumes:
  av_postgres-data:
  av_minio_data:
  av_mongo_data:
