# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        dotnet restore ./backend/MainService/AnimalVolunteerBackend.sln
        dotnet restore ./backend/FileService/FileService.sln
      
    - name: Build
      run: |
        dotnet build --no-restore ./backend/MainService/AnimalVolunteerBackend.sln
        dotnet build --no-restore ./backend/FileService/FileService.sln
